;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   mar. sep. 5 2023
; Processor: PIC18F4550
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include "p18f4550.inc" ; Incluye el archivo de definición de registros

;====================================================================
; VARIABLES
;====================================================================
; Configuración del PIC18F4550
CONFIG WDT=OFF, LVP=OFF, MCLRE=OFF

; Definición de constantes
LCD_RS  EQU 0x1B    ; Puerto para RS del LCD
LCD_E   EQU 0x1A    ; Puerto para E del LCD
LCD_D4  EQU 0x1D    ; Puerto para D4 del LCD
LCD_D5  EQU 0x1C    ; Puerto para D5 del LCD
LCD_D6  EQU 0x1F    ; Puerto para D6 del LCD
LCD_D7  EQU 0x1E    ; Puerto para D7 del LCD
BMP280_SDI EQU 0x33 ; Puerto para SDI del BMP280
BMP280_SDO EQU 0x34 ; Puerto para SDO del BMP280
BMP280_SCK EQU 0x35 ; Puerto para SCK del BMP280
BMP280_CSB EQU 0x36 ; Puerto para CSB del BMP280
DHT22_PIN  EQU 0x17  ; Puerto para el DHT22

; Zona de Datos
CBLOCK 0x20
    Temp_DHT22         ; Variable para la temperatura del DHT22
    Presion_BMP280      ; Variable para la presión del BMP280
    Humedad_DHT22       ; Variable para la humedad del DHT22
ENDC

;====================================================================
; PROGRAMA PRINCIPAL
;====================================================================

ORG 0x00
GOTO Inicio

; Rutina de Inicialización
Inicio:
    ; Configuración de puertos
    MOVLW 0x07
    MOVWF TRISB     ; Configurar puertos B como salida
    MOVLW 0xF0
    MOVWF TRISC     ; Configurar puertos C como salida
    MOVLW 0x00
    MOVWF TRISA     ; Configurar puertos A como salida

    ; Configuración del LCD
    CALL InicializarLCD

    ; Leer datos del BMP180 y DHT22
    CALL LeerBMP280
    CALL LeerDHT22

    ; Mostrar datos en el LCD
    CALL MostrarDatosLCD

Loop:
    GOTO Loop

; Rutina para inicializar el LCD
InicializarLCD:
    ; Inicialización del LCD
    ; ...


    RETURN

; Rutina para leer datos del BMP280
LeerBMP280:
    ; Comunicación con BMP280 (SPI)
    ; ...

    ; Almacenar los datos en Temp_BMP280 y Presion_BMP280
    ; ...

    RETURN

; Rutina para leer datos del DHT22
LeerDHT22:
    ; Comunicación con DHT22
    ; ...

    ; Almacenar la humedad en Humedad_DHT22
    ; ...

    RETURN

; Rutina para mostrar datos en el LCD
MostrarDatosLCD:
    ; Mostrar datos en el LCD
    ; ...

    RETURN

; Otras rutinas y subrutinas necesarias

; Fin del programa
END